lyrics_list =  ['You are the dancing queen\nYoung and sweet\nOnly seventeen',
                'Dancing queen\nFeel the beat from the tambourine, oh yeah',
                'You can dance\nYou can jive\nHaving the time of your life',
                'Ooh, see that girl\nWatch that scene\nDig in the dancing queen',
                'Knowing me, knowing you (a-ha)\nThere is nothing we can do',
                'Knowing me, knowing you (a-ha)\nWe just have to face it this time we\'re through',
                'Breaking up is never easy, I know\nBut I have to go\nKnowing me, knowing you',
                'If you change your mind, I\'m the first in line\nHoney I\'m still free\nTake a chance on me',
                'Gonna do my very best and it ain\'t no lie\nIf you put me to the test, if you let me try',
                'Take a chance on me',
                'Mamma mia, here I go again\nMy my, how can I resist you?\nMamma mia, does it show again\nMy my, just how much I\'ve missed you?',
                'Yes, I\'ve been brokenhearted\nBlue since the day we parted',
                'Don\'t go wasting your emotion\nLay all your love on me\nDon\'t go sharing your devotion\nLay all your love on me',
                'Tonight the super trouper lights are gonna find me',
                'I have a dream, a song to sing\nTo help me cope with anything','If you see the wonder of a fairy tale\nYou can take the future even if you fail',
                'I believe in angels\nSomething good in everything I see',
                'I don\'t want to talk\nAbout the things we\'ve gone through\nThough it\'s hurting me\nNow it\'s history',
                'I\'ve played all my cards\nAnd that\'s what you\'ve done too\nNothing more to say\nNo more ace to play',
                'The winner takes it all\nThe loser standing small\nBeside the victory\nThat\'s her destiny',
                'Money, money, money\nMust be funny\nIn the rich man\'s world',
                'Money, money, money\nAlways sunny\nIn the rich man\'s world',
                'All the things I could do\nIf I had a little money\nIt\'s a rich man\'s world',
                'So when you\'re near me, darling can\'t you hear me\nS. O. S.',
                'The love you gave me, nothing else can save me\nS. O. S.','When you\'re gone\nHow can I even try to go on?',
                'Try once more like you did before\nSing a new song, Chiquitita'
                'The stars were bright, Fernando\nThey were shining there for you and me\nFor liberty, Fernando',
                'Though I never thought that we could lose\nThere\'s no regret\nIf I had to do the same again\nI would, my friend, Fernando',
                'If I had to do the same again\nI would, my friend, Fernando',
                'Voulez-vous (ah-ha)\nTake it now or leave it (ah-ha)\nNow it\'s all we get (ah-ha)\nNothing promised, no regrets',
                'Voulez-vous (ah-ha)\nAin\'t no big decision (ah-ha)\nYou know what to do (ah-ha)\nLa question c\'est; voulez-vous',
                'Take me through the darkness\nTo the break of the day',
                'Gimme, gimme, gimme a man after midnight\nThere\'s not a soul out there\nNo one to hear my prayer',
                'Take it easy (take it easy)\nBetter slow down girl\nThat\'s no way to go\nDoes your mother know',
                'Take it easy (take it easy)\nTry to cool it girl\nTake it nice and slow\nDoes your mother know',
                'What\'s the name of the game?\nDoes it mean anything to you?',
                'What\'s the name of the game?\nCan you feel it the way I do?\nTell me please, \'cause I have to know',
                'I\'m a bashful child, beginning to grow\nAnd you make me talk\nAnd you make me feel',
                'And you make me show\nWhat I\'m trying to conceal\nIf I trust in you, would you let me down?',
                'Would you laugh at me, if I said I care for you?\nCould you feel the same way too?',
                'I wanna know\nOh yes I wanna know','So I say\nThank you for the music, the songs I\'m singing',
                'Thanks for all the joy they\'re bringing\nWho can live without it, I ask in all honesty',
                'What would life be?\nWithout a song or a dance what are we?',
                'So how could I ever refuse\nI feel like I win when I lose\nWaterloo couldn\'t escape if I wanted to',
                'Waterloo knowing my fate is to be with you\nWaterloo finally facing my Waterloo',
                'Oh, oh Waterloo finally facing my Waterloo\nWaterloo I was defeated, you won the war',
                'If you\'re all alone\nWhen the pretty birds have flown\nHoney, I\'m still free\nTake a chance on me',
                'Take a chance on me\nThat\'s all I ask of you, honey\nTake a chance on me',
                'You say that I waste my time\nBut I can\'t get you off my mind, no, I can\'t let go\n\'Cause I love you so',
                'Super trouper beams are gonna blind me\nBut I won\'t feel blue\nLike I always do\n\'Cause somewhere in the crowd there\'s you',
                'I have a dream, a fantasy\nTo help me through reality\nAnd my destination makes it worth the while\nPushing through the darkness still another mile',
                'Chiquitita, you and I know\nHow the heartaches come and they go and the scars they\'re leaving\nYou\'ll be dancing once again and the pain will end\nYou will have no time for grieving']


yes_or_no_personal = {'Voulez-vous (ah-ha)\nTake it now or leave it (ah-ha)\nNow it\'s all we get (ah-ha)\nNothing promised, no regrets',
                      'Voulez-vous (ah-ha)\nAin\'t no big decision (ah-ha)\nYou know what to do (ah-ha)\nLa question c\'est; voulez-vous',
                      'Take it easy (take it easy)\nBetter slow down girl\nThat\'s no way to go\nDoes your mother know',
                      'Take it easy (take it easy)\nTry to cool it girl\nTake it nice and slow\nDoes your mother know',
                      'I believe in angels\nSomething good in everything I see',
                      'Breaking up is never easy, I know\nBut I have to go\nKnowing me, knowing you\nIt\'s the best I can do',
                      'If you\'re all alone\nWhen the pretty birds have flown\nHoney, I\'m still free\nTake a chance on me',
                      'Take a chance on me\nThat\'s all I ask of you, honey\nTake a chance on me',
                      'If you see the wonder of a fairy tale\nYou can take the future even if you fail',
                      'Take a chance on me',
                      'Breaking up is never easy, I know\nBut I have to go\nKnowing me, knowing you'
                      'Gonna do my very best and it ain\'t no lie\nIf you put me to the test, if you let me try',
                      'I\'ve played all my cards\nAnd that\'s what you\'ve done too\nNothing more to say\nNo more ace to play'}


sad = {'You are the dancing queen\nYoung and sweet\nOnly seventeen',
       'Dancing queen\nFeel the beat from the tambourine, oh yeah',
       'You can dance\nYou can jive\nHaving the time of your life',
       'I have a dream, a fantasy\nTo help me through reality\nAnd my destination makes it worth the while\nPushing through the darkness still another mile',
       'Try once more like you did before\nSing a new song, Chiquitita',
       'Though I never thought that we could lose\nThere\'s no regret\nIf I had to do the same again\nI would, my friend, Fernando',
       'I have a dream, a song to sing\nTo help me cope with anything',
       'Knowing me, knowing you (a-ha)\nWe just have to face it this time we\'re through',
       'Super trouper beams are gonna blind me\nBut I won\'t feel blue\nLike I always do\n\'Cause somewhere in the crowd there\'s you',
       'Gonna do my very best and it ain\'t no lie\nIf you put me to the test, if you let me try',
       'Don\'t go wasting your emotion\nLay all your love on me\nDon\'t go sharing your devotion\nLay all your love on me'}

waterloo = {'So how could I ever refuse\nI feel like I win when I lose\nWaterloo couldn\'t escape if I wanted to',
            'Waterloo knowing my fate is to be with you\nWaterloo finally facing my Waterloo',
            'Oh, oh Waterloo finally facing my Waterloo\nWaterloo I was defeated, you won the war'}

why_what = {'What would life be?\nWithout a song or a dance what are we?',
            'What\'s the name of the game?\nDoes it mean anything to you?',
            'What\'s the name of the game?\nCan you feel it the way I do?\nTell me please, \'cause I have to know'}

love = {'I\'m a bashful child, beginning to grow\nAnd you make me talk\nAnd you make me feel',
        'Would you laugh at me, if I said I care for you?\nCould you feel the same way too?',
        'Gimme, gimme, gimme a man after midnight\nThere\'s not a soul out there\nNo one to hear my prayer',
        'If you change your mind, I\'m the first in line\nHoney I\'m still free\nTake a chance on me',
        'You say that I waste my time\nBut I can\'t get you off my mind, no, I can\'t let go\n\'Cause I love you so',
        'So when you\'re near me, darling can\'t you hear me\nS. O. S.',
        'The love you gave me, nothing else can save me\nS. O. S.','When you\'re gone\nHow can I even try to go on?',
        'When you\'re gone\nHow can I even try to go on?',
        'Mamma mia, here I go again\nMy my, how can I resist you?\nMamma mia, does it show again\nMy my, just how much I\'ve missed you?',
        'Yes, I\'ve been brokenhearted\nBlue since the day we parted',
        'I don\'t want to talk\nAbout the things we\'ve gone through\nThough it\'s hurting me\nNow it\'s history'}

money = {'Money, money, money\nMust be funny\nIn the rich man\'s world',
         'Money, money, money\nAlways sunny\nIn the rich man\'s world',
         'All the things I could do\nIf I had a little money\nIt\'s a rich man\'s world'}

default = {'I have a dream, a song to sing\nTo help me cope with anything',
           'I believe in angels\nSomething good in everything I see',
           'When you\'re gone\nHow can I even try to go on?',
           'What would life be?\nWithout a song or a dance what are we?',
           'Take me through the darkness\nTo the break of the day',
           'Tonight the super trouper lights are gonna find me'}